import { Heading } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading as="h1">Titre de la page</Heading>
        Page principale
      </main>

      <footer>Pied de page</footer>
    </>
  );
};

export default Home;
